#2/Update readme
lightning-resume/template-navy-react pull request #3
Opened 2021-08-17 16:31 UTC by chekuda

2021-08-18 12:54 UTC, oxmanroman requested changes

2021-08-18 12:54 UTC, oxmanroman commented on README.md
> +# :zap Template Navy React
This should be
` # :zap: Template Navy React`

2021-08-18 12:54 UTC, oxmanroman commented on README.md
> +This template has been created for the use of the AMAZING [https://github.com/lightning-resume/lightning-resume]lightning-resume project
I believe you wanted the links to show in a different way, please take a look [here](https://github.com/lightning-resume/template-navy-react/tree/2/Update-readme)

You should do something like: [my text](https://blabla.com \)

2021-08-19 09:02 UTC, 0xGorilla commented
Could you please add a screenshot to the README?

2021-08-19 09:03 UTC, 0xGorilla commented on README.md
> +The template reads the JSON generated by [lightning-resume project](https://github.com/lightning-resume/lightning-resume).
```
The template reads the JSON generated by [linkedin-resume-parser](https://github.com/lightning-resume/linkedin-resume-parser).
```

2021-08-20 09:51 UTC, oxmanroman approved these changes

2021-08-20 09:52 UTC, merged